### ISSUE TITLE
Ability to enable or disable patching at boot time

### ISSUE THREAD

**Issue by Aeris1One** [PretendoNetwork/Inkay#12]
There is an option available on Aroma's Plugin Config Menu to enable or disable connection to Pretendo network, there's also a notification "Using Pretendo Network" to ensure we are aware that the console uses Pretendo.

Would it be possible to implement an option to enable or disable patching at boot time ?

Something like : 
1. The console starts and show user selection menu
2. A notification "Using [Pretendo/Nintendo] Network, hold ⊝ to connect to [Nintendo/Pretendo] Network" appears depending on where you're connecting
3. If ⊝ is held, the console reboots and the "Use Pretendo" setting is switched on or off

Aroma Updater works similar to this by sending a notification "An update is available, click on ⊕ to start Updater", so detecting a button input while in user selection should be possible.
Code to check combo pressed is here : https://github.com/wiiu-env/AromaBasePlugin/blob/ea5f427d51b93d1b4ad506c8dcd3100db5feebb9/src/UpdaterCheck.cpp#L107

**Comment by ashquarky** [comment]
This isn't a bad idea, unfortunately I only saw it after switching to NN got a lot less useful - would people still want this?

**Comment by jonbarrow** [comment]
Cleaning up some older issues and looking for ones to add to our task tracker. @ashquarky is this something we want to move forward with or should this be closed? There's not much reason to switch back to NN now outside of eShop purchases?

**Comment by ashquarky** [comment]
eShop purchases is the only real usecase, and I've not seen much interest for this. Will close for now, still open to adding it if there's demand.
