### ISSUE TITLE
Error Code: 102-2482

### ISSUE THREAD

**Issue by falin24** [PretendoNetwork/Inkay#15]
I use aroma and I try to use Inkay and Miiverse  Inkay go good but Miiverse give me that error I got banned? Let me Know please

**Comment by ashquarky** [comment]
This doesn't sound like an Inkay problem. What's your PNID?

**Comment by falin24** [comment]
Mu PNID is guests

**Comment by falin24** [comment]
Traduction an error has appared try again later if the problem continues contact with the support and say the error for more information go to the manual.

**Comment by falin24** [comment]
Sorry for bad english

**Comment by falin24** [comment]
And miiverse can be to the public or i need to buy suscription
