### ISSUE TITLE
Does Pretendo not use the system proxy server?

### ISSUE THREAD

**Issue by LittleFIve233** [PretendoNetwork/Inkay#19]
Does Pretendo not use the system proxy server?
Due to some special problems, it is not possible to connect to pretendo in China.

**Comment by ashquarky** [comment]
That's actually an interesting question. As far as I know, all of our stuff *should* use the system proxy, but some games (Ubisoft ones) don't.
Can you say which part is giving problems? I assume account setup?

**Comment by LittleFIve233** [comment]
> That's actually an interesting question. As far as I know, all of our stuff _should_ use the system proxy, but some games (Ubisoft ones) don't. Can you say which part is giving problems? I assume account setup?

On 3ds, when using nibms to switch pretendo, no matter what you do, an error 001-0105 will be reported and you cannot connect to the network.
On Wiiu, when using inkay, only miiverse is normal. Changing user information and game server seem to be unable to work normally.
The above all use the system proxy server.

**Comment by ashquarky** [comment]
Changing user information on wiiu is not implemented yet, unrelated to proxy or no proxy.

Game servers work via NEX and raw UDP packets instead of via HTTP, which is outside the system proxy - this was true for Nintendo Network too, though. I would expect error 106-0502 in that case - is that what you see?

I'm not sure what we can do about it, since the Wii U only supports HTTP proxies instead of e.g. SOCKS5, which could relay the UDP packets for NEX. A VPN might also work here if you have that option available.

**Comment by UiharuNeko** [comment]
In China, some local operators block domain names they consider suspicious by using SNI detection. They actively insert an RST after initiating a TLS handshake, causing the connection to be interrupted.
![image](https://github.com/PretendoNetwork/Inkay/assets/23272727/7b95b121-8224-4722-9f2e-bed08730c9a6)

**Comment by ashquarky** [comment]
> In China, some local operators block domain names they consider suspicious by using SNI detection. They actively insert an RST after initiating a TLS handshake, causing the connection to be interrupted. ![image](https://private-user-images.githubusercontent.com/23272727/323682099-7b95b121-8224-4722-9f2e-bed08730c9a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0OTAyODcsIm5iZiI6MTcxMzQ4OTk4NywicGF0aCI6Ii8yMzI3MjcyNy8zMjM2ODIwOTktN2I5NWIxMjEtODIyNC00NzIyLTlmMmUtYmVkMDg3MzBjOWE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDAxMjYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1OTViNjI3YmVhNGQ1MTQyOTMxNDM1MTVjMTE2YzI4MjlhNDAwNDZhMzc2ZmY2OTVlMDJhMDU5ODUzZDE3NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-ofdSagJpENrTfgvUBCicmulAz_yCZy0fvtx6UzfgJk)

I'll have to check with the server people, but I don't think we can really avoid using SNI without major changes. If we did, would they just start sinkholing our IP or overwriting DNS responses, too?

**Comment by UiharuNeko** [comment]
> > In China, some local operators block domain names they consider suspicious by using SNI detection. They actively insert an RST after initiating a TLS handshake, causing the connection to be interrupted. ![image](https://private-user-images.githubusercontent.com/23272727/323682099-7b95b121-8224-4722-9f2e-bed08730c9a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0OTAyODcsIm5iZiI6MTcxMzQ4OTk4NywicGF0aCI6Ii8yMzI3MjcyNy8zMjM2ODIwOTktN2I5NWIxMjEtODIyNC00NzIyLTlmMmUtYmVkMDg3MzBjOWE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDAxMjYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1OTViNjI3YmVhNGQ1MTQyOTMxNDM1MTVjMTE2YzI4MjlhNDAwNDZhMzc2ZmY2OTVlMDJhMDU5ODUzZDE3NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-ofdSagJpENrTfgvUBCicmulAz_yCZy0fvtx6UzfgJk)
> 
> I'll have to check with the server people, but I don't think we can really avoid using SNI without major changes. If we did, would they just start sinkholing our IP or overwriting DNS responses, too?

That might happen. It's essentially a game of cat and mouse; there isn't a universal method to solve this problem.

**Comment by ashquarky** [comment]
Given the amount of "raw UDP" stuff the Wii U uses (from the ISP's perspective, anyway) and how I don't think we can stop the console from sending SNI info, I think the best bet for users in China is to put their entire console behind a VPN that wraps every packet - e.g. making a WiFi hotspot from a PC with a VPN enabled. OP got most of the way there with a HTTP proxy, but proxying NEX/UDP is likely required too.

If full VPNs are somehow unavailable, there might not be much we can do...

**Comment by jonbarrow** [comment]
I agree with Quarky here. Those issues seem pretty out of scope for us. Should this be closed then?

**Comment by ashquarky** [comment]
I'll close this, happy to re-open if the CN users can specify something they'd like us to do for them.
