### ISSUE TITLE
Pretendo plugin doesn’t show up/isn’t recognized on Wii U 

### ISSUE THREAD

**Issue by AlsoVincent** [PretendoNetwork/Inkay#20]
I put the inkay-pretendo.wps file into the correct aroma plugins folder, but it isn’t showing up in the plugins menu and isn’t being recognized by the Wii U at all. I tried using different versions of inkay, but that didn’t work either.

**Comment by ashquarky** [comment]
Check the Aroma Updater - are you using the latest version? Can you specify which folder you put the file into? Are there other plugins in that folder?

**Comment by AlsoVincent** [comment]
Just checked my system, turns out I was on an outdated version of aroma. Thanks for the help!!
