### ISSUE TITLE
Error 118-0513 or 118-xxxx on Splatoon

### ISSUE THREAD

**Issue by TakeSora25** [PretendoNetwork/Inkay#22]
Hi :3
well, the problem is, i can connect to the servers, i can play mario kart 7 on my 3ds whitout problems, but i cant play Splatoon, even when i see the news, an error with the 118-xxxx comes in, and i really want to play T.T
As i know, many people have the same problem... I have moderated NAT, but the only game i cant play online at the moment is splatoon... Please Help T.T

**Comment by has207** [comment]
I was finally able to make Splatoon work by using the SSSL DNS server in addition to installing Inkay. As I understand it this shouldn't be necessary so seems like a bug with Inkay..?

Sadly there is nobody actually playing from what I saw, which I guess is at least in part due to the fact that it only works with custom DNS right now.

**Comment by TakeSora25** [comment]
The DNS is not the problem i think, when i dont have the Nimble.rpx, the game asks to actualize the news, but i cant see them, after i put the nimble.rpx in the sd, i see the news, but the error 118-xxxx comes...
And, when i try a few times, and i am the only one in a ¨Room¨ i see how the clock ads time, like someone is triyng to reach, to access, to connect with me, but no one does.... 
Today i try to play Mario Kart 8, and the same problem comes, i cant connect to other consoles, in the wii u at least, in 3ds i play flawlessly T.T
Someone can help??? T.T
Sorry for my bad english, greetings from Venezuela /o/

**Comment by has207** [comment]
Okay so the situation I have is:

- with Inkay only, Splatoon doesn't load news and skips right to the plaza, going into lobby gives server error, so no online play appears possible
- with Inkay + SSSL DNS server set, news loads and you can get into the lobby but trying to join a match just hangs forever until finally erroring out

Private matches between two WiiUs with Inkay+SSSL works as expected.

I haven't tried adding nimble, seems like it should be unnecessary at this stage..? But it sounds like that's still broken regardles sadly

**Comment by TakeSora25** [comment]
Can you try to play mario kart??? And put the default dns in the wii u and the nimble in the sd??? 
Pd: I cant connect to the mario maker servers either....

**Comment by has207** [comment]
MK8 works okay for me with just Inkay

**Comment by has207** [comment]
Okay I got Splatoon working with online matching, you need to set the DNS server and install 30_nimble.rpx in addition to having the Inkay install. But I'm finally getting into matches and there seems to be more people playing now on pretendo than on the nintendo network before it went offline!

**Comment by TakeSora25** [comment]
My situation T.T

With Inkay only, Splatoon doesn't load news and skips right to the plaza, going into lobby gives server error, so no online play appears possible, MK8 have the error 118-0513.

With Inkay + SSSL DNS server set, news loads and you can get into the lobby but trying to join a match just hangs forever until finally erroring out, MK8 have the same error T.T

With Inkay + SSSL DNS server set + nimble, news loads and you can get into the lobby but trying to join a match just hangs forever until finally erroring out, error 118-0513 in MK8.

Can you add me to try a Private matche??? My mii is TakeSoraVe and mi pnid is TakeSora2508

**Comment by ashquarky** [comment]
Inkay + Nimble is the suggested setup for homebrewed consoles, *not* SSSL. I know we keep changing it so it's understandable to think Nimble isn't needed, but as of the NN shutdown it is required again.

101-0502 is your console being unable to connect to Friends - probably it was down from being overloaded, or your internet connection is blocking NEX?

**Comment by TakeSora25** [comment]
As i know, no, is not blocking...
For a moment i think it was a collision problem with the dns and the nimble at the same time, but now i put just the nimble and still have errors... I cant play Splatoon yet T.T
Maybe the server have a firewall policy that drop certain packages??? And mine are in that group???

**Comment by has207** [comment]
@ashquarky thanks for clarifying, is there any reason nimble isn't mentioned at all on what I thought was the official setup guide? https://pretendo.network/docs/install/wiiu

@TakeSora25 have you tried removing Inkay and nimble and just using custom DNS? That setup also works well (i.e. Splatoon match making works) on my homebrew setup and initial login seems to be a couple seconds faster than with Inkay

**Comment by ashquarky** [comment]
> @ashquarky thanks for clarifying, is there any reason nimble isn't mentioned at all on what I thought was the official setup guide? https://pretendo.network/docs/install/wiiu

https://github.com/PretendoNetwork/website/pull/271

**Comment by jonbarrow** [comment]
Cleaning up some older issues here. Errors like these are out of scope for this repository imo, @ashquarky what say you? Inkay doesn't really have anything to do with these connections
