### ISSUE TITLE
Recent Aroma Update broke Inkay's (Unregistered Wara Wara Plaza BOSS tasks) function  

### ISSUE THREAD

**Issue by FourHawk** [PretendoNetwork/Inkay#27]
The Recent Aroma update now causes a issue with inkay, this may be due to the fact that the plug in system was changed with the beta 17 update and may now be causing issues

**Comment by ashquarky** [comment]
@MaschellDev said:
> Also this check is broken in Inkay: https://github.com/PretendoNetwork/Inkay/blob/b239ae82db1dbdf8d303e9892f899c91766a7d59/src/config.cpp#L67-L69
> It's only called once when the plugin is loaded. Depending on when you load the plugin, you may get different result. The new Aroma won't be loaded on Wii U Menu but already in H&S, so this function will always return false

Definitely a bug.

**Comment by TraceEntertains** [comment]
Should be fixed in #28
