### ISSUE TITLE
Change "Skip Pretendo Network Patches" to "enable/disable" or similar

### ISSUE THREAD

**Issue by InternalLoss** [PretendoNetwork/Inkay#3]
This is a personal opinion, but it feels like "Skip = false" (having false be the default state) makes it awkward for users, especially when other Aroma plugins (notably the region free plugin) have defaults be true; instead of "skip patches", maybe "Connect to Pretendo Network" or something similar that's more user friendly?

I assume the "true/false" is not changable, as otherwise I'd recommend "Nintendo/Pretendo" :)

**Comment by ashquarky** [comment]
Fixed in [38e9322](https://github.com/PretendoNetwork/Inkay/commit/38e9322e0a78a690773a4feb9ad06748be1ac636)
