### ISSUE TITLE
[Bug]: Inkay compatability issues with Aroma beta-21

### ISSUE THREAD

**Issue by JouriR** [PretendoNetwork/Inkay#35]
### Checked Existing

- [X] I have checked the repository for duplicate issues.

### What happened?

I had not used my Wii U in a while and got greeted with a message saying I needed to update my Aroma environment. I did this using the "Aroma Updater" to beta-21. After I rebooted the console everything was still okay so I headed to the "Homebrew App Store" and updated Inkay to v2.5.0. After this I rebooted the console again, but it would not load into the Wii U menu anymore. It will show the loading screen and play the background music, but that's everything. That will keep showing forever.

I also posted in the Discord [(link to the thread)](https://discord.com/channels/408718485913468928/1259535539414106186/1259535539414106186) server about this and someone told me to downgrade back to Aroma beta-20, that indeed solved the issue. So I assume something changed between beta-20 and beta-21 making Inkay incompatable again.

### What did you expect to happen?

After updating Inkay, I expected my console to still boot into the menu.

### Steps to reproduce?

1. Update Aroma to beta-21 using the Aroma Updater app.
2. Reboot console
3. Update Inkay plugin to v2.5.0 using the Homebrew App Store
4. Reboot console

After step 4 this issue should happen.

### Other relevant information. (OPTIONAL)

When I was still on beta-21 and the issue was happening, I was still able to boot into the Tiramisu environment successfully by holding the X button on boot and selecting Tiramisu from the menu.

Also, I don't know if it's possible, but is there some way I can make a debug build of Inkay that can output errors to the screen? If one occurs of course. Because then I may be able to provide you all with some more info, or maybe even take a look at it myself! :)

**Comment by eku** [comment]
Do you have any other plugins active in your aroma setup?
Just to make sure that they don't affect.

BTW I can't reproduce the error.

**Comment by JouriR** [comment]
Hmmm yes, I do also have some other plugins installed. I can post a list of them later tonight and check with the people in the Discord if they have some of the same plugins as me.

**Comment by eku** [comment]
Remove `sntp client`.

**Comment by JouriR** [comment]
Yes, thank you. I just found that out as well. Do you have any idea what happened to it? Since I can't find any record of it anymore online or in the homebrew store.

I still think it's weird tho how the issue only started happening after updating Inkay.
