### ISSUE TITLE
[Question]: Inkay build

### ISSUE THREAD

**Issue by 00cedke** [PretendoNetwork/Inkay#37]
### Checked Existing

- [x] I have checked the repository for duplicate issues.

### What would you like to know?

Hello, sorry for disturb but i want to build Inkay myself, i have devkitpro with the features and Dockerfile but i can't build Inkay i don't know why, please i need a help, thanks for your reponse.

**Comment by 00cedke** [comment]
![Capture](https://github.com/user-attachments/assets/cf7aaaba-00bd-422a-b4a2-43744e4c1877)

**Comment by MatthewL246** [comment]
The problem is that you're just not using the right commands to build and run the image. Try this.

```
docker build . -t inkay-builder
docker run -it --rm -v .:/app inkay-builder
```

**Comment by 00cedke** [comment]
i put this command and inkay will be compiled ?

**Comment by MatthewL246** [comment]
Yes, those commands should just compile Inkay in the current directory.

**Comment by 00cedke** [comment]
![Capture](https://github.com/user-attachments/assets/a621f0c5-a33a-4273-9bae-e0c501ed64a2)

**Comment by MatthewL246** [comment]
That error message is already pretty clear. You need to start Docker.

**Comment by 00cedke** [comment]
how ??

**Comment by 00cedke** [comment]
ohh i open docker and its worked

**Comment by 00cedke** [comment]
ig

**Comment by 00cedke** [comment]
the first command worked but the second ewwww no
![Capture](https://github.com/user-attachments/assets/4219eece-adea-450a-bd78-ba92dfb528fd)

**Comment by MatthewL246** [comment]
That's because you're not using the same image name for both commands. `inkay-build` and `inkay-builder` aren't the same. I would recommend taking a look at a Docker beginner's tutorial so you can better understand how Docker images and containers work.

**Comment by ashquarky** [comment]
This user's fork strips out our GPLv3 license and copyright messages, instead putting their own BSD (more permissive!) license and their own copyright attribution: https://github.com/InnoverseTeam/Innoverse-patcher/blob/main/LICENSE

As such we won't be providing further support. Clones and forks are reminded that they must abide by the code sharing and attribution rules of the GPL.
