### ISSUE TITLE
[Feature]: Post blogs in the Notification Center if possible

### ISSUE THREAD

**Issue by ProjectDreadman** [PretendoNetwork/Inkay#44]
### Checked Existing

- [X] I have checked the repository for duplicate issues.

### What feature do you want to see added?

I want to see if it's possible to post the pretendo blogs in the notification center so instead of going to the website people can just head to the Notification Center and check out the blog

### Why do you want to have this feature?

So it will be easier and more simpler for people to check out the blogs. Like if they don't have access to web browser they can just go to the notification center and check out the blogs and see what new features and games have been added

**Comment by ExperiencersInternational** [comment]
It's likely not possible to send a full blog post, but Pretendo could do a QR code to link to the blog. You need access to a web browser anyways to install Pretendo and links to new blog entries are posted on Discord, Mastodon, Twitter and the forums.

https://forum.pretendo.network/t/could-you-send-the-pretendo-blog-through-spotpass-notifications/5642/6?u=gamersinternatio

**Comment by jonbarrow** [comment]
This is not a feature for Inkay. Notifications are sent via SpotPass which is powered by the BOSS server. Got both consoles. Check if an existing feature request already exists on that repo and if not, this should be moved there

**Comment by ProjectDreadman** [comment]
Ok mb
