### ISSUE TITLE
[Bug]: Enabling Inkay causes GiveMiiYouTube Plugin to not function correctly

### ISSUE THREAD

**Issue by playerjmr** [PretendoNetwork/Inkay#45]
### Checked Existing

- [X] I have checked the repository for duplicate issues.

### What happened?

When launching YouTube with Inkay enabled, YouTube hangs. Disabling Inkay allows for it to work.

### What did you expect to happen?

YouTube should launch properly as expected since it did not use nintendo network.

### Steps to reproduce?

1. Enable Inkay
2. Download GiveMiiYouTube plugin
3. Launch YouTube

**Comment by jonbarrow** [comment]
Can you confirm that YouTube doesn't work with GiveMiiYouTube disabled? The only thing GiveMiiYouTube does is tell YouTube that it got a token from the server which Nintendo no longer hands out. However we control the servers, so we can give YouTube this token

**Comment by playerjmr** [comment]
> Can you confirm that YouTube doesn't work with GiveMiiYouTube disabled? The only thing GiveMiiYouTube does is tell YouTube that it got a token from the server which Nintendo no longer hands out. However we control the servers, so we can give YouTube this token

theres actually no way to disable the plugin except if you remove it from the SD card

**Comment by jonbarrow** [comment]
Then remove it from the SD card. The goal is to just run the YouTube app without GiveMiiYouTube at all. However that has to happen

**Comment by playerjmr** [comment]
> Then remove it from the SD card. The goal is to just run the YouTube app without GiveMiiYouTube at all. However that has to happen

YouTube still does not run even with givemiiyoutube disabled

**Comment by jonbarrow** [comment]
That's the error code I was looking for. Try now?

**Comment by playerjmr** [comment]
it gave me this (inkay on, givemiiyoutube off) ![WIN_20240926_01_04_31_Pro](https://github.com/user-attachments/assets/4e89e996-6f7b-42fd-accd-02bc4c5d6802)

**Comment by playerjmr** [comment]
@jonbarrow hi, its me again. turns out due to my negligence, I improperly transferred all of my saves from my NNID to my PNID (I used FTPii and forgot to reboot the console after save transfer) which is causing the issue with youtube not booting. deleting the save using FTPii made it work again. Sorry for the trouble.
