### ISSUE TITLE
[Bug]: Wii U Chat ERROR : 102-2482 

### ISSUE THREAD

**Issue by theDSi2homebrewGuy** [PretendoNetwork/Inkay#51]
### Checked Existing

- [X] I have checked the repository for duplicate issues.

### What happened?

I am getting this error when trying to load Wii U chat, I do not know what is causing the error, if anyone has information on how to fix this error please help me, thanks in advance, theDSi2homebrewGuy

### What did you expect to happen?

I expected it to load into Wii U chat so I could call my non-existent friends.

### Other relevant information. (OPTIONAL)

I use the free tier

**Comment by coopeeo** [comment]
This error is when the servers don't respond with a service token, and if this happens, the application will then show that error then prompt you to close. Now Wii U Chat is supported but only on beta servers (aka supporter server meaning you need a subscription), I think the reason that Pretendo said is that it's very unreliable (don't quote me on that). That is why you get an error code of 102-2482 when loading into Wii U Chat.

**Comment by ashquarky** [comment]
https://pretendo.network/docs/error/102-2482
