### ISSUE TITLE
[Regression]: Wii U hangs when accessing the "Change User Information" screen

### ISSUE THREAD

**Issue by DimitriPilot3** [PretendoNetwork/Inkay#55]
### Checked Existing

- [X] I have checked the repository for duplicate issues.

### What happened?

I've made a PNID on the Pretendo website and linked it to a Wii U account, using the Inkay nightly (ebecf95) at the time. If I select that account, then tap the Mii icon in the top left and tap "Change User Information", the screen fades into a loading screen with the Wii U logo in the lower-right corner, then gets stuck. The little tune keeps playing but the spinner (throbber) won't appear, forcing me to power off the system.

This is a softlock rather than a hard crash. The L+Down+Minus combo doesn't work, yet the ftpiiu plugin still does. I ran [WiiUCrashLogDumper](https://github.com/wiiu-env/WiiUCrashLogDumper) before and after the softlock, but nothing new was generated.

**EDIT:** Since 6c78a95, the softlock only occurs when trying to access the applet a second time without a prior reboot.

### What was the previous functionality?

Prior to f4aeee80, the applet loads and doesn't softlock, ever.

### When did this occur?

According to `git bisect`:

1. Sometime between f4aeee80 and ea71879b (around the time of the plugin/module split)
2. 727f11d0 (indirectly) caused another regression that appears to have been fixed in 6c78a95

### Other relevant information. (OPTIONAL)

Wii U: 32GB Samsung MMC, system version 5.5.5E, 2GB SD card (FAT32 with 16k cluster size), Aroma beta 22 is installed, Nimble is also installed.

During `git bisect`, I made sure to add or delete `Inkay-pretendo.wms` to or from `/wiiu/environments/aroma/modules` when testing newer or older revisions; I also do update the plugin in `/wiiu/environments/aroma/plugins` and do a full restart of the system via homebrew.

**Comment by ashquarky** [comment]
Pulling in @DaniElectra

**Comment by DaniElectra** [comment]
Hmm... I can replicate the issue, and when entering the account settings applet it seems to not be reaching `WUMS_APPLICATION_STARTS` *at all*?

This is strange, considering it was working for me at the beginning of the PR, so I would think it must have broken later

**Comment by DimitriPilot3** [comment]
Attached below is a log of the issue being reproduced on ebecf95 (latest), thanks to a modification I made to `ftpiiu_plugin` that lets me crash the console remotely:

- [66.log](https://github.com/user-attachments/files/18137624/66.log) (built by running `make`)
- [68.log](https://github.com/user-attachments/files/18137640/68.log) (built by running `make DEBUG=1` after fixing some trivial compilation errors)

The relevant titleid (Account Settings) in my case is `000500101004B200` and gets loaded in starting at line 430-465 (respectively) in the logs.

In `66.log` I see that all of the modules load fine, except Inkay for some reason which didn't print anything;

In `68.log` I see that the Inkay module does in fact load properly; the Inkay start-up message was not being printed earlier as it used the conditional macro `DEBUG_FUNCTION_LINE_VERBOSE` which is enabled with `make DEBUG=1` (but not with `make DEBUG=VERBOSE`):
```
00;01;06;054: Running KernelModule v0.2.2
... 8 lines trimmed ...
00;01;06;078: Running ContentRedirectionModule v0.2.7
00;01;06;078: [(M)             Inkay][               main.cpp]                  __wums_start@L0207: Inkay v2.6.0 starting up...

00;01;06;079: [(M)             Inkay][           olv_urls.cpp]                setup_olv_libs@L0075: Inkay: no olv, quitting for now

00;01;06;079: [(M)             Inkay][   account_settings.cpp]          patchAccountSettings@L0125: Inkay: hewwo account settings!

00;01;06;182: [(M)             Inkay][        replace_mem.cpp]                       replace@L0032: found str @1050e56d: saccount.nintendo.net
00;01;06;182: [(M)             Inkay][        replace_mem.cpp]                       replace@L0034: new str   @1050e56d: saccount.pretendo.cc
00;01;06;288: [(M)             Inkay][        replace_mem.cpp]                       replace@L0032: found str @1052bee4: https
00;01;06;288: [(M)             Inkay][        replace_mem.cpp]                       replace@L0034: new str   @1052bee4: https
00;01;06;289: Running RPXLoadingModule v0.3.4
00;01;06;354: Running WiiUPluginLoaderBackend v0.3.4
00:01:06:526: ISFS: fs_ops.c(613)Invalid inode name homebrew_logging.rpl
00:01:06:526: ISFS: fs_ops.c(613) Invalid inode name homebrew_logging.rpl
00:01:06:530: ISFS: fs_ops.c(613)Invalid inode name homebrew_logging.rpl
00:01:06:530: ISFS: fs_ops.c(613) Invalid inode name homebrew_logging.rpl
00;01;06;409: Error: Could not load acquired RPL "homebrew_logging".
00;01;06;409: WHBLogModuleInit: OSDynLoad_Acquire failed.
00;01;06;413: Error: Could not load acquired RPL "homebrew_logging".
00;01;06;413: WHBLogModuleInit: OSDynLoad_Acquire failed.
00:01:06:564: ACP: Mounting "/vol/save/" on "/vol/storage_mlc01/usr/save/00050010/1004b200/user/"
00:01:06:564: ACP: Mount done (0)
00;01;06;454: FS: Updated volume state of client 0x12ba91f5 to FS_VOLSTATE_FATAL(10)
00;01;06;454: FS: by error -196646.
00;01;06;454: FS: READ_FILE      upid:[15] sts:[INVALID_FILE_HANDLE] hnd:[0x9d0000] dst:[0x00000000] size:[1] cnt:[0] pos:[0]
00;01;06;455: FS: current dir:[/].
```

**Comment by eku** [comment]
According to the commit message the WiiU still freezes if the applet is opened for the second time. Any plans to fix this:

**Comment by ashquarky** [comment]
Yes, we want account settings to work fully. Closing the issue before was an accident.

**Comment by ashquarky** [comment]
@DimitriPilot3 Can you try the Inkay build from https://github.com/PretendoNetwork/Inkay/actions/runs/12366236686 - seems to fix it for me

**Comment by DimitriPilot3** [comment]
@ashquarky Same here, I can't reproduce it anymore after 38f1b18. Great work :)
