### ISSUE TITLE
main.cpp: change “hewwo” to “hello”

### ISSUE THREAD

**Issue by kurbus** [PretendoNetwork/Inkay#7]
I like furries as much as the next guy but come on
And also sex no longer funny, everybody go home
Pls no write access removal

**Comment by kurbus** [comment]
I’m sorry Ash

**Comment by SuperMarioDaBom** [comment]
Not sure why you seem to believe "hewwo" is more than just a silly greeting. No, it is not exclusive to furry circles, and no it has no further implications.
Please note that if this change is included in #6 , it will be denied as it is irrelevant to the pr.
